name: laba4
on: 
  push: 
    branches: "main"
jobs: 
  sborka:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: buildlibrary
        run: |
          mkdir build
          cd build
          cmake ..
          cmake --build .
      - name: openhelloworldapplication
        run: |
          cd build/hello_world_application
          ./hello_world
      - name: opensolver
        run: |
          cd build/solver_appplication
          ./solverexe 
          2 2 2
          
          
